In [1]:
import numpy as np
import pandas as pd

all_data = pd.read_csv('voice.csv')
features = [feat for feat in all_data.columns if feat != 'label']
output = 'label'
all_data[output].replace(['male','female'], [1, 0], inplace = True)
all_samples = all_data[features].values
labels = all_data[output].values
all_samples = all_samples.T
#print(all_samples.shape)

In [2]:
mean_vector = np.zeros((20,1))
for i in range(20):
    mean = np.mean(all_samples[i,:])
    mean_vector[i] += mean

print('Mean vector:\n', mean_vector)

Mean vector:
 [[  0.18090661]
 [  0.05712596]
 [  0.18562068]
 [  0.14045559]
 [  0.22476496]
 [  0.08430937]
 [  3.14016752]
 [ 36.56846079]
 [  0.89512706]
 [  0.40821641]
 [  0.1652818 ]
 [  0.18090661]
 [  0.14280673]
 [  0.03680181]
 [  0.25884225]
 [  0.82921096]
 [  0.05264705]
 [  5.04727674]
 [  4.99462969]
 [  0.17375151]]


In [4]:
scatter_matrix = np.zeros((20,20))
#print(len(all_samples[:,i].T))
#print(all_samples.shape[0])
for i in range(all_samples.shape[1]):
    scatter_matrix += (all_samples[:,i].T - mean_vector).dot((all_samples[:,i].T - mean_vector).T)
#print('Scatter Matrix:\n', scatter_matrix)



In [34]:
#cov_mat = np.cov([all_samples[0,:],all_samples[1,:], all_samples[2,:]])
#print('Covariance Matrix:\n', cov_mat)

In [5]:
eig_val_sc, eig_vec_sc = np.linalg.eig(scatter_matrix)

# eigenvectors and eigenvalues for the from the covariance matrix
#eig_val_cov, eig_vec_cov = np.linalg.eig(cov_mat)

for i in range(len(eig_val_sc)):
    eigvec_sc = eig_vec_sc[:,i].reshape(1,20).T
    #eigvec_cov = eig_vec_cov[:,i].reshape(1,20).T
    #assert eigvec_sc.all() == eigvec_cov.all(), 'Eigenvectors are not identical'

    print('Eigenvector {}: \n{}'.format(i+1, eigvec_sc))
    print('Eigenvalue {} from scatter matrix: {}'.format(i+1, eig_val_sc[i]))
    #print('Eigenvalue {} from covariance matrix: {}'.format(i+1, eig_val_cov[i]))
    #print('Scaling factor: ', eig_val_sc[i]/eig_val_cov[i])
    print(40 * '-')


Eigenvector 1: 
[[-0.2236068]
 [-0.2236068]
 [-0.2236068]
 [-0.2236068]
 [-0.2236068]
 [-0.2236068]
 [-0.2236068]
 [-0.2236068]
 [-0.2236068]
 [-0.2236068]
 [-0.2236068]
 [-0.2236068]
 [-0.2236068]
 [-0.2236068]
 [-0.2236068]
 [-0.2236068]
 [-0.2236068]
 [-0.2236068]
 [-0.2236068]
 [-0.2236068]]
Eigenvalue 1 from scatter matrix: 1235397828.9595625
----------------------------------------
Eigenvector 2: 
[[ 0.07078099]
 [ 0.07427509]
 [ 0.07064792]
 [ 0.07192284]
 [ 0.06954294]
 [ 0.07350775]
 [-0.01275355]
 [-0.95637321]
 [ 0.05061985]
 [ 0.06436444]
 [ 0.07122205]
 [ 0.07078099]
 [ 0.07185648]
 [ 0.0748488 ]
 [ 0.068581  ]
 [ 0.05248054]
 [ 0.07440152]
 [-0.06658776]
 [-0.06510163]
 [ 0.07098296]]
Eigenvalue 2 from scatter matrix: 79515099.53440629
----------------------------------------
Eigenvector 3: 
[[-0.18531639]
 [-0.04413063]
 [ 0.25409659]
 [ 0.21638866]
 [ 0.08350985]
 [-0.17312286]
 [-0.2418362 ]
 [ 0.00316823]
 [-0.13845365]
 [-0.15838608]
 [-0.34627129]
 [-0.17966156]
 [ 

In [31]:
#for item in eig_vec_sc:
   # np.testing.assert_array_almost_equal(1.0, np.linalg.norm(item))

In [6]:
eig_pairs = [[np.real(eig_val_sc[i]),eig_vec_sc[:,i]] for i in range(len(eig_val_sc))]

eig_pairs.sort(key = lambda x: x[0], reverse = True)
#eig_pairs.real

#for j in range(20):
    #eig_pairs[j][1] = eig_pairs[j][1].real
    #print(eig_pairs[0][1].real)
for i in eig_pairs:
    print(i[0])

#print(len(eig_pairs[0][1]))

1235397828.9595625
79515099.53440629
9.664112320492072e-07
7.809629583537764e-07
5.693062675719105e-07
5.088868199374355e-07
3.858604117262074e-07
3.1887836891012464e-07
2.2052752452424404e-07
1.730274177245567e-07
1.4740649666042747e-08
-3.424548577471856e-08
-1.2934855739089137e-07
-1.8120953920528832e-07
-3.2017664613850837e-07
-3.5549787323355783e-07
-4.600304503444154e-07
-6.218723123567269e-07
-7.130270906593734e-07
-7.663873425660817e-07


In [7]:
#matrix_w = np.zeros((10,3168))
#print(matrix_w)
matrix_w = np.hstack((eig_pairs[0][1].reshape(20,1), eig_pairs[1][1].reshape(20,1)))
for i in range(2,10):
    matrix_w = np.hstack((matrix_w, eig_pairs[i][1].reshape(20,1)))
print("Matrix W:\n", matrix_w)

Matrix W:
 [[-0.2236068   0.07078099 -0.18531639  0.3038605   0.02669513 -0.14470454
   0.07527984 -0.01858156  0.06045399  0.02124684]
 [-0.2236068   0.07427509 -0.04413063  0.22955252  0.29270921  0.09734729
  -0.1757234   0.02093595  0.27776336  0.15561667]
 [-0.2236068   0.07064792  0.25409659 -0.09757689 -0.20594793 -0.06336594
  -0.28469804  0.01532077 -0.35536957  0.20621448]
 [-0.2236068   0.07192284  0.21638866 -0.28524072 -0.09440766  0.26265571
  -0.11392115  0.32398845  0.03184024  0.13536316]
 [-0.2236068   0.06954294  0.08350985  0.18617986 -0.1082577   0.44946204
  -0.48641407 -0.42259708 -0.23002762 -0.08522363]
 [-0.2236068   0.07350775 -0.17312286 -0.13102782  0.17829481 -0.45842036
  -0.37686598  0.15610128 -0.04691556 -0.36830748]
 [-0.2236068  -0.01275355 -0.2418362   0.19894332 -0.08093492  0.01382096
  -0.05763833  0.09657286 -0.11695989  0.19168591]
 [-0.2236068  -0.95637321  0.00316823 -0.04814777  0.07164638 -0.04141889
   0.01047896  0.02306864 -0.00307894  0

In [8]:
transformed = matrix_w.T.dot(all_samples)
#print(transformed.shape)
assert transformed.shape == (10,3168), "The matrix is not 10x3168 dimensional."
#print(transformed)
transformed = transformed.T

In [9]:
#Sigmoid funciont

def nonlin(x, deriv = False):
    if (deriv == True):
       return x * (1 - x)
    else:
       return 1/(1 + np.exp(-x))

In [10]:
#Split dataset into training dat and test data

#all_data = pd.read_csv('voice.csv')
features = [feat for feat in all_data.columns if feat != 'label']
output = 'label'
num_datapoints = len(transformed)

#Training data is first 90% of male and female
#Test data is las 10% of male and female

test_male = int(1584 * 0.1)
test_female = int((num_datapoints-1584) * 0.1)

#all_data[output].replace(['male','female'], [1, 0], inplace = True)

train_data_male = transformed[0:(1583-test_male)]
train_data_female = transformed[1584:-test_female]
test_data_male = transformed[(1583 - test_male):1583]
test_data_female = transformed[-test_female:]

train_data = np.concatenate((train_data_male, train_data_female), axis = 0)
test_data = np.concatenate((test_data_male, test_data_female),axis = 0)

train_labels_male = all_data[output].iloc[0:(1583 - test_male)].values
train_labels_female = all_data[output].iloc[1584:-test_female].values
test_labels_male = all_data[output].iloc[(1583 - test_male):1583].values 
test_labels_female = all_data[output].iloc[-test_female:].values

train_labels = np.concatenate((train_labels_male, train_labels_female), axis = 0)
test_labels = np.concatenate((test_labels_male, test_labels_female), axis = 0)

print(len(train_data))
print(len(test_data))

2851
316


In [19]:
#To ensure random number of every loop is the same
np.random.seed(10)
#Initialize weights
syn0 = 2 * np.random.random((10,1)) - 1
l0 = train_data
#Keep updating weights
for iter in range(1000000):
    #l0 = train_data
    #Input(l0) with weights(syn0) 
    #Combined by sigmoid function
    l1 = nonlin(np.dot(l0,syn0))
    
    #How different that l1 from exact labels
    l1_error = train_labels.T - l1.T
    
    #l1_delta = l1_error.T * nonlin(l1, True)
    #syn0 += np.dot(l0.T, l1_delta)
    syn0 += np.dot(l0.T, l1_error.T)
print(l1)

[[ 1.]
 [ 1.]
 [ 1.]
 ..., 
 [ 0.]
 [ 0.]
 [ 0.]]


In [20]:
count_0 = 0
count_1 = 0
for i in l1:
    if 0 in i:
       count_0 += 1
    else:
       count_1 += 1
print("predicted number of female", count_0)
print("predicted number of male", count_1)
print("total number of train data:",count_0 + count_1)

predicted number of female 1839
predicted number of male 1012
total number of train data: 2851


In [21]:
correct_predic = 0
wrong_predic = 0
for i in range(0,2851):
    if train_labels[i] == l1[i]:
       correct_predic += 1
    else:
       wrong_predic += 1
    
print("Number of correct prediction", correct_predic)
print("Number of wrong prediction", wrong_predic)

Number of correct prediction 2257
Number of wrong prediction 594


In [22]:
print("Correct rate is: ")
print(correct_predic/(wrong_predic+correct_predic))

Correct rate is: 
0.7916520519116099


In [23]:
l0 = test_data
   
l1 = nonlin(np.dot(l0,syn0))
    

In [24]:
count_0 = 0
count_1 = 0
for i in l1:
    if 0 in i:
       count_0 += 1
    else:
       count_1 += 1
print("predicted number of female", count_0)
print("predicted number of male", count_1)
print("total number of train data:",count_0 + count_1)

predicted number of female 250
predicted number of male 66
total number of train data: 316


In [25]:
correct_predic = 0
wrong_predic = 0
for i in range(0,316):
    if test_labels[i] == l1[i]:
       correct_predic += 1
    else:
       wrong_predic += 1
    
print("Number of correct prediction", correct_predic)
print("Number of wrong prediction", wrong_predic)

Number of correct prediction 217
Number of wrong prediction 99


In [26]:
print("Correct rate is: ", correct_predic/(wrong_predic + correct_predic))

Correct rate is:  0.6867088607594937
