In [1]:
import numpy as np
import pandas as pd

all_data = pd.read_csv('voice.csv')
features = [feat for feat in all_data.columns if feat != 'label']
output = 'label'
all_data[output].replace(['male','female'], [1, 0], inplace = True)
all_samples = all_data[features].values
labels = all_data[output].values
all_samples = all_samples.T

print(type(all_samples[1][1]))
#print(all_samples.shape)



<class 'numpy.float64'>


In [2]:
mean_vector = np.zeros((20,1))
for i in range(20):
    mean = np.mean(all_samples[i,:])
    mean_vector[i] += mean

print('Mean vector:\n', mean_vector)

Mean vector:
 [[  0.18090661]
 [  0.05712596]
 [  0.18562068]
 [  0.14045559]
 [  0.22476496]
 [  0.08430937]
 [  3.14016752]
 [ 36.56846079]
 [  0.89512706]
 [  0.40821641]
 [  0.1652818 ]
 [  0.18090661]
 [  0.14280673]
 [  0.03680181]
 [  0.25884225]
 [  0.82921096]
 [  0.05264705]
 [  5.04727674]
 [  4.99462969]
 [  0.17375151]]


In [16]:
scatter_matrix = np.zeros((20,20))
#print(len(all_samples[:,i].T))
#print(all_samples.shape[0])
for i in range(all_samples.shape[1]):
    scatter_matrix += (all_samples[:,i].reshape(20,1) - mean_vector).dot((all_samples[:,i].reshape(20,1) - mean_vector).T)
#print('Scatter Matrix:\n', scatter_matrix)



In [17]:
#cov_mat = np.cov([all_samples[0,:],all_samples[1,:], all_samples[2,:]])
#print('Covariance Matrix:\n', cov_mat)

In [18]:
eig_val_sc, eig_vec_sc = np.linalg.eig(scatter_matrix)

# eigenvectors and eigenvalues for the from the covariance matrix
#eig_val_cov, eig_vec_cov = np.linalg.eig(cov_mat)

for i in range(len(eig_val_sc)):
    eigvec_sc = eig_vec_sc[:,i].reshape(1,20).T
    #eigvec_cov = eig_vec_cov[:,i].reshape(1,20).T
    #assert eigvec_sc.all() == eigvec_cov.all(), 'Eigenvectors are not identical'

    print('Eigenvector {}: \n{}'.format(i+1, eigvec_sc))
    print('Eigenvalue {} from scatter matrix: {}'.format(i+1, eig_val_sc[i]))
    #print('Eigenvalue {} from covariance matrix: {}'.format(i+1, eig_val_cov[i]))
    #print('Scaling factor: ', eig_val_sc[i]/eig_val_cov[i])
    print(40 * '-')


Eigenvector 1: 
[[ -7.00771761e-05]
 [  4.27241402e-05]
 [ -6.55942518e-05]
 [ -1.26314495e-04]
 [ -2.60997808e-05]
 [  1.00214715e-04]
 [  3.06914983e-02]
 [  9.99477044e-01]
 [ -4.25065720e-05]
 [  1.44660854e-04]
 [ -2.32694403e-04]
 [ -7.00771761e-05]
 [ -4.65719063e-05]
 [ -2.89465801e-05]
 [ -1.02112630e-05]
 [ -1.18093479e-03]
 [ -4.84226068e-05]
 [ -7.16974913e-03]
 [ -7.12132653e-03]
 [ -1.81684617e-04]]
Eigenvalue 1 from scatter matrix: 57717930.60811337
----------------------------------------
Eigenvector 2: 
[[  2.79522351e-03]
 [ -1.38305120e-03]
 [  2.92346128e-03]
 [  3.79994217e-03]
 [  1.51789019e-03]
 [ -2.28205197e-03]
 [ -3.56031744e-02]
 [  1.12602547e-02]
 [ -3.45207796e-03]
 [ -1.55012663e-02]
 [  6.10401319e-03]
 [  2.79522351e-03]
 [  1.55641272e-03]
 [  1.09205411e-03]
 [  2.25203765e-03]
 [  8.31407406e-02]
 [ -1.50612885e-04]
 [  7.03910264e-01]
 [  7.04060877e-01]
 [ -1.24758709e-02]]
Eigenvalue 2 from scatter matrix: 73246.71461201172
---------------------

In [19]:
#for item in eig_vec_sc:
   # np.testing.assert_array_almost_equal(1.0, np.linalg.norm(item))

In [25]:
eig_pairs = [[np.abs(eig_val_sc[i]),eig_vec_sc[:,i]] for i in range(len(eig_val_sc))]

eig_pairs.sort(key = lambda x: x[0], reverse = True)
#eig_pairs.real

#for j in range(20):
    #eig_pairs[j][1] = eig_pairs[j][1].real
    #print(eig_pairs[0][1].real)
for i in eig_pairs:
    print(i[0])

#print(len(eig_pairs[0][1]))

57717930.6081
73246.714612
2503.78260901
294.967876889
89.8697851531
30.1490302924
15.3840734404
10.386573435
5.05980948395
3.33952481046
2.69480319109
1.53552784326
0.80942615084
0.567664516246
0.496941999971
0.085629249735
0.0192571995521
7.89345906233e-11
1.87645684557e-12
3.83753153508e-15


In [7]:
#matrix_w = np.zeros((10,3168))
#print(matrix_w)
matrix_w = np.hstack((eig_pairs[0][1].reshape(20,1), eig_pairs[1][1].reshape(20,1)))
for i in range(2,10):
    matrix_w = np.hstack((matrix_w, eig_pairs[i][1].reshape(20,1)))
print("Matrix W:\n", matrix_w)

Matrix W:
 [[-0.2236068   0.07078099 -0.18531639  0.3038605   0.02669513 -0.14470454
   0.07527984 -0.01858156  0.06045399  0.02124684]
 [-0.2236068   0.07427509 -0.04413063  0.22955252  0.29270921  0.09734729
  -0.1757234   0.02093595  0.27776336  0.15561667]
 [-0.2236068   0.07064792  0.25409659 -0.09757689 -0.20594793 -0.06336594
  -0.28469804  0.01532077 -0.35536957  0.20621448]
 [-0.2236068   0.07192284  0.21638866 -0.28524072 -0.09440766  0.26265571
  -0.11392115  0.32398845  0.03184024  0.13536316]
 [-0.2236068   0.06954294  0.08350985  0.18617986 -0.1082577   0.44946204
  -0.48641407 -0.42259708 -0.23002762 -0.08522363]
 [-0.2236068   0.07350775 -0.17312286 -0.13102782  0.17829481 -0.45842036
  -0.37686598  0.15610128 -0.04691556 -0.36830748]
 [-0.2236068  -0.01275355 -0.2418362   0.19894332 -0.08093492  0.01382096
  -0.05763833  0.09657286 -0.11695989  0.19168591]
 [-0.2236068  -0.95637321  0.00316823 -0.04814777  0.07164638 -0.04141889
   0.01047896  0.02306864 -0.00307894  0

In [8]:
transformed = matrix_w.T.dot(all_samples)
#print(transformed.shape)
assert transformed.shape == (10,3168), "The matrix is not 10x3168 dimensional."
#print(transformed)
transformed = transformed.T

In [9]:
#Sigmoid funciont

def nonlin(x, deriv = False):
    if (deriv == True):
       return x * (1 - x)
    else:
       return 1/(1 + np.exp(-x))

In [10]:
#Split dataset into training dat and test data

#all_data = pd.read_csv('voice.csv')
features = [feat for feat in all_data.columns if feat != 'label']
output = 'label'
num_datapoints = len(transformed)

#Training data is first 90% of male and female
#Test data is las 10% of male and female

test_male = int(1584 * 0.1)
test_female = int((num_datapoints-1584) * 0.1)

#all_data[output].replace(['male','female'], [1, 0], inplace = True)

train_data_male = transformed[0:(1583-test_male)]
train_data_female = transformed[1584:-test_female]
test_data_male = transformed[(1583 - test_male):1583]
test_data_female = transformed[-test_female:]

train_data = np.concatenate((train_data_male, train_data_female), axis = 0)
test_data = np.concatenate((test_data_male, test_data_female),axis = 0)

train_labels_male = all_data[output].iloc[0:(1583 - test_male)].values
train_labels_female = all_data[output].iloc[1584:-test_female].values
test_labels_male = all_data[output].iloc[(1583 - test_male):1583].values 
test_labels_female = all_data[output].iloc[-test_female:].values

train_labels = np.concatenate((train_labels_male, train_labels_female), axis = 0)
test_labels = np.concatenate((test_labels_male, test_labels_female), axis = 0)

print(len(train_data))
print(len(test_data))

2851
316


In [19]:
#To ensure random number of every loop is the same
np.random.seed(10)
#Initialize weights
syn0 = 2 * np.random.random((10,1)) - 1
l0 = train_data
#Keep updating weights
for iter in range(1000000):
    #l0 = train_data
    #Input(l0) with weights(syn0) 
    #Combined by sigmoid function
    l1 = nonlin(np.dot(l0,syn0))
    
    #How different that l1 from exact labels
    l1_error = train_labels.T - l1.T
    
    #l1_delta = l1_error.T * nonlin(l1, True)
    #syn0 += np.dot(l0.T, l1_delta)
    syn0 += np.dot(l0.T, l1_error.T)
print(l1)

[[ 1.]
 [ 1.]
 [ 1.]
 ..., 
 [ 0.]
 [ 0.]
 [ 0.]]


In [20]:
count_0 = 0
count_1 = 0
for i in l1:
    if 0 in i:
       count_0 += 1
    else:
       count_1 += 1
print("predicted number of female", count_0)
print("predicted number of male", count_1)
print("total number of train data:",count_0 + count_1)

predicted number of female 1839
predicted number of male 1012
total number of train data: 2851


In [21]:
correct_predic = 0
wrong_predic = 0
for i in range(0,2851):
    if train_labels[i] == l1[i]:
       correct_predic += 1
    else:
       wrong_predic += 1
    
print("Number of correct prediction", correct_predic)
print("Number of wrong prediction", wrong_predic)

Number of correct prediction 2257
Number of wrong prediction 594


In [22]:
print("Correct rate is: ")
print(correct_predic/(wrong_predic+correct_predic))

Correct rate is: 
0.7916520519116099


In [23]:
l0 = test_data
   
l1 = nonlin(np.dot(l0,syn0))
    

In [24]:
count_0 = 0
count_1 = 0
for i in l1:
    if 0 in i:
       count_0 += 1
    else:
       count_1 += 1
print("predicted number of female", count_0)
print("predicted number of male", count_1)
print("total number of train data:",count_0 + count_1)

predicted number of female 250
predicted number of male 66
total number of train data: 316


In [25]:
correct_predic = 0
wrong_predic = 0
for i in range(0,316):
    if test_labels[i] == l1[i]:
       correct_predic += 1
    else:
       wrong_predic += 1
    
print("Number of correct prediction", correct_predic)
print("Number of wrong prediction", wrong_predic)

Number of correct prediction 217
Number of wrong prediction 99


In [26]:
print("Correct rate is: ", correct_predic/(wrong_predic + correct_predic))

Correct rate is:  0.6867088607594937
